from django.urls import path
from . import views
from django.views.generic import TemplateView as generic_view
from django.contrib.auth import views as auth_view
from django.conf import settings

urlpatterns=[
    path('' ,views.Home ,name='home'),
    path('analyze_data/', views.analyze_data, name='analyze_data'),
    path('create_account/', views.create_account, name='create_account'),
    path('user_login/', views.user_login, name='user_login'),
    path('log_out/', views.log_out, name='log_out'),
    path('confirm/<int:order_id>', views.confirm, name='confirm'),
    path('favorite/', views.favorite, name='favorite'),
    path('reset_info/', views.reset_info, name='reset_info'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('res_home/<int:res_id>/', views.res_home, name='res_home'),
    path('descrement_item/<int:item_id>/', views.descrement_item, name='descrement_item'),
    path('increment_item/<int:item_id>/', views.increment_item, name='increment_item'),
    path('deleteAll_items/<int:item_id>/', views.deleteAll_items, name='deleteAll_items'),
    path('add_product/', views.add_product, name='add_product'),
    path('update_product/<int:product_id>', views.update_product, name='update_product'),
    path('siparislerim/', views.siparislerim, name='siparislerim'),
    path('deliver/', views.deliver, name='deliver'),
    path('take_order/', views.take_order, name='take_order'),
    path('deliveier_status/', views.deliveier_status, name='deliveier_status'),
    path('active_order/', views.active_order, name='active_order'),
    path('d_order_delivred/', views.d_order_delivred, name='d_order_delivred'),
    path('active_wallet/', views.active_wallet, name='active_wallet'),
    path('add_item_toOrder/', views.add_item_toOrder, name='add_item_toOrder'),
    path('Orders/', views.Orders, name='Orders'),
    path('addressler/', views.addressler, name='addressler'),
    path('add_adress/', views.add_adress, name='add_adress'),
    path('Res_favorite/', views.Res_favorite, name='Res_favorite'),
    path('payment/', views.payment, name='payment'),
    path('tip/', views.tip, name='tip'),
    path('messager', views.messager, name='messager'),
    path('message_container/<int:user_id>', views.message_container, name='message_container'),
    path('send_message', views.send_message, name='send_message'),
    path('user_message/<int:res_id>', views.user_message, name='user_message'),
    path('res_send_message', views.res_send_message, name='res_send_message'),
    path('tip-later/', views.tip_later, name='tip_later'),  
    path('Order_tooked/<int:order_id>', views.Order_tooked, name='Order_tooked'),
    path('canceled/<int:order_id>', views.canceled, name='canceled'),
    path('forout/<int:order_id>', views.forout, name='forout'),
    path('delivred/<int:order_id>', views.delivred, name='delivred'),
    path('confirm_productUpdate/', views.confirm_productUpdate, name='confirm_productUpdate'),
    path('order_confirm/<int:order_id>/', views.order_confirm, name='order_confirm'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('order_complet/<int:order_id>/', views.order_complet, name='order_complet'),
    path('complet/<int:order_id>/', views.complet, name='complet'),
    path('profile/', generic_view.as_view(template_name='registration/profile.html'), name='profile'),
    path('accounts/login' ,auth_view.LogoutView.as_view(template_name='registration/login.html') ,name='login'),    

]