# Generated by Django 5.0.4 on 2025-01-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
