# Generated by Django 5.0.4 on 2025-01-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0003_restaurant_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_message',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
