# Generated by Django 5.0.4 on 2025-01-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0004_remove_user_message_date_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='user_message',
            name='date',
            field=models.TimeField(auto_now=True),
        ),
    ]
