# Generated by Django 5.0.4 on 2025-01-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0005_remove_order_date_user_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
