# Generated by Django 5.0.4 on 2025-01-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0006_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_delivier',
            field=models.BooleanField(default=False),
        ),
    ]
