# Generated by Django 5.0.4 on 2025-01-05 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0007_alter_customuser_is_delivier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='order_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Order_Deliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delivered', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='orders_images/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
