# Generated by Django 5.0.4 on 2025-01-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0008_customuser_order_quantity_order_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_accepted_fd',
            field=models.BooleanField(default=False),
        ),
    ]
