# Generated by Django 5.0.4 on 2025-01-12 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0009_order_is_accepted_fd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='order_quantity',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active_f_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order_deliver',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliver', to='Jib.order'),
        ),
    ]
