# Generated by Django 5.0.4 on 2025-01-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0010_remove_customuser_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_it_banned',
            field=models.BooleanField(default=False),
        ),
    ]
