# Generated by Django 5.0.4 on 2025-01-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0011_customuser_is_it_banned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_it_banned',
            new_name='is_ban',
        ),
    ]
