# Generated by Django 5.0.4 on 2025-01-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0013_order_deliver_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_deliver',
            name='num',
        ),
        migrations.AddField(
            model_name='customuser',
            name='deliver_num',
            field=models.IntegerField(default=0),
        ),
    ]
