# Generated by Django 5.0.4 on 2025-01-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0016_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='tip',
        ),
    ]
