# Generated by Django 5.0.4 on 2025-01-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0017_remove_wallet_tip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='deliver_price',
            new_name='value',
        ),
    ]
