# Generated by Django 5.0.4 on 2025-01-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0018_rename_deliver_price_wallet_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Toplam',
            field=models.IntegerField(default=0),
        ),
    ]
