# Generated by Django 5.0.4 on 2025-01-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0019_order_toplam'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivred_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
