# Generated by Django 5.0.4 on 2025-01-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jib', '0020_order_delivred_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='orders_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
